# Oak-D on Husarion Panthers
camera_intrinsics:
  fx: 759.8603515625
  fy: 759.8603515625
  cx: 637.9826049804688
  cy: 358.5901794433594

# Rotation and translation parameters for the camera-IMU setup.
camera_imu_transform:
  # Rotation from camera frame to IMU frame (in degrees)
  R_cam_imu: [-90, 90, 0]
  # Pitch rotation from camera frame to IMU frame (in degrees)
  R_pitch: [0, 0, 0]
  # Translation vector from camera frame to IMU frame (in meters)
  t1: [0.0, 0.0, 0.75]
  # Rotation from camera frame to BEV frame (in degrees)
  R2: [-180, 0, 90]
  # Translation vector from camera frame to BEV frame (in meters)
  t2: [4.20, 0.0, 6.0]